import { db, initializeDatabase } from "@/lib/db";
import crypto from "node:crypto";
const now="2026-08-29T19:18:00.000Z", id=(x:string)=>x;
const event=(caseId:string,type:string,label:string,at:string,institutionId:string|null="inst-hdfc")=>db.prepare("INSERT INTO case_events VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(crypto.randomUUID(),caseId,type,"system",null,institutionId,JSON.stringify({label,simulated:true}),JSON.stringify({}),JSON.stringify({}),1,at,at);
export function seedDemo(reset=false) { initializeDatabase(); if(reset) db.exec("DELETE FROM audit_logs; DELETE FROM notifications; DELETE FROM case_events; DELETE FROM fund_movements; DELETE FROM transactions; DELETE FROM evidence_requests; DELETE FROM evidence; DELETE FROM agency_assignments; DELETE FROM fir_records; DELETE FROM incidents; DELETE FROM cases; DELETE FROM citizens; DELETE FROM users; DELETE FROM institutions;"); const exists=db.prepare("SELECT id FROM cases LIMIT 1").get(); if(exists) return;
 const users=[['user-asha','citizen@demo.onecase.in','Asha Mehta','citizen'],['user-priya','operator@demo.onecase.in','Priya Nair','operator'],['user-rohan','citizen2@demo.onecase.in','Rohan Shah','citizen'],['user-neha','citizen3@demo.onecase.in','Neha Kapoor','citizen'],['user-omar','citizen4@demo.onecase.in','Omar Khan','citizen']]; for(const u of users) db.prepare("INSERT INTO users VALUES(?,?,?,?,?,?)").run(...u,now,now);
 const institutions=[['inst-sbi','SBI (simulated)','bank','SBI','Bengaluru','Karnataka',1,now],['inst-hdfc','HDFC Bank — Fraud Response (simulated)','bank','HDFC','Mumbai','Maharashtra',1,now],['inst-icici','ICICI Bank — Fraud Response (simulated)','bank','ICICI','Mumbai','Maharashtra',1,now],['inst-cyber','Bengaluru Cyber Crime Unit (simulated)','cyber_cell','BLR-CCU','Bengaluru','Karnataka',1,now],['inst-police','Bengaluru Cyber Crime Police Station (simulated)','police','BCPS','Bengaluru','Karnataka',1,now]]; for(const i of institutions) db.prepare("INSERT INTO institutions VALUES(?,?,?,?,?,?,?,?)").run(...i);
 const citizens=[['cit-asha','user-asha','Asha Mehta','+91 •••• 4408','Bengaluru','Karnataka','en',now],['cit-rohan','user-rohan','Rohan Shah','+91 •••• 0139','Pune','Maharashtra','en',now],['cit-neha','user-neha','Neha Kapoor','+91 •••• 2350','Delhi','Delhi','en',now],['cit-omar','user-omar','Omar Khan','+91 •••• 1620','Hyderabad','Telangana','en',now]]; for(const c of citizens) db.prepare("INSERT INTO citizens VALUES(?,?,?,?,?,?,?,?)").run(...c);
 const cs=[['case-golden','NCRP-26-847193','cit-asha','Financial cyber fraud','PARTIALLY_SECURED','urgent',48500,31200,12000,5300,'bank','HDFC Bank — fraud response team','FUNDS TRACING','2026-08-29T18:42:00.000Z',now,null,now,now],['case-b','NCRP-26-781304','cit-rohan','Investment scam','INVESTIGATION','high',375000,0,375000,0,'government','Pune Cyber Crime Unit','INVESTIGATION',now,now,null,now,now],['case-c','NCRP-26-553921','cit-neha','Marketplace fraud','FIR_REVIEW','medium',18900,18900,0,0,'police','Delhi Cyber Crime Unit','FIR REVIEW',now,now,null,now,now],['case-d','NCRP-26-420187','cit-omar','OTP / account takeover','FINANCIAL_INTERVENTION','urgent',82000,0,82000,0,'bank','SBI (simulated)','FINANCIAL INTERVENTION',now,now,null,now,now]]; for(const c of cs) db.prepare("INSERT INTO cases VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(...c);
 db.prepare("INSERT INTO incidents VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run('inc-golden','case-golden','Someone claiming to be from SBI said KYC was expiring and asked me to install an APK sent over WhatsApp. ₹48,500 was transferred.','Bank impersonation with malicious APK and unauthorised transfer.','Financial cyber fraud','Bank impersonation + malicious APK','SBI (simulated)','UPI / bank transfer','2026-08-29T17:42:00.000Z','2026-08-29T18:42:00.000Z','Bengaluru',0.92,now,now);
 for(const c of cs.slice(1)) db.prepare("INSERT INTO incidents VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`inc-${c[0]}`,c[0],'Synthetic demo incident','Synthetic structured incident',c[3],c[3],null,'Bank transfer',now,now,'Synthetic',0.8,now,now);
 const tx=[['tx-source','case-golden',null,'SIM-SBI-48500','inst-sbi','outbound',48500,'upi','identified','2026-08-29T17:42:00.000Z','HDFC ••9281','SBI ••4408','{}',now],['tx-hdfc','case-golden','tx-source','SIM-HDFC-31200','inst-hdfc','inbound',31200,'transfer','secured','2026-08-29T17:43:00.000Z','HDFC ••9281','SBI ••4408','{}',now],['tx-icici','case-golden','tx-source','SIM-ICICI-6700','inst-icici','inbound',6700,'transfer','tracing','2026-08-29T17:44:00.000Z','ICICI ••1834','HDFC ••9281','{}',now],['tx-trace','case-golden','tx-source','SIM-HDFC-5300','inst-hdfc','inbound',5300,'transfer','tracing','2026-08-29T17:44:00.000Z','HDFC ••9281','SBI ••4408','{}',now],['tx-atm','case-golden','tx-source','SIM-ATM-5300','inst-hdfc','outbound',5300,'atm','withdrawn','2026-08-29T17:48:00.000Z','ATM withdrawal','HDFC ••9281','{}',now]]; for(const t of tx) db.prepare("INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(...t);
 const mv=[['mv-one','case-golden','tx-source','tx-hdfc',31200,'secured','2026-08-29T18:52:00.000Z',now],['mv-two','case-golden','tx-source','tx-icici',6700,'tracing','2026-08-29T18:53:00.000Z',now],['mv-three','case-golden','tx-source','tx-trace',5300,'tracing','2026-08-29T18:54:00.000Z',now],['mv-four','case-golden','tx-source','tx-atm',5300,'unrecovered','2026-08-29T18:55:00.000Z',now]]; for(const m of mv) db.prepare("INSERT INTO fund_movements VALUES(?,?,?,?,?,?,?,?)").run(...m);
 const events:[string,string,string,string|null][]=[['CASE_CREATED','Complaint received','2026-08-29T18:42:00.000Z',null],['INCIDENT_CLASSIFIED','Your report was structured for financial intervention','2026-08-29T18:43:00.000Z',null],['TRANSACTION_IDENTIFIED','Transaction identified from your supplied details','2026-08-29T18:44:00.000Z','inst-sbi'],['SENDER_BANK_NOTIFIED','Sender bank notified through simulated integration','2026-08-29T18:45:00.000Z','inst-sbi'],['BENEFICIARY_BANK_IDENTIFIED','Beneficiary bank identified','2026-08-29T18:46:00.000Z','inst-hdfc'],['FREEZE_REQUEST_CREATED','Freeze request sent to beneficiary bank','2026-08-29T18:47:00.000Z','inst-hdfc'],['FUNDS_PARTIALLY_SECURED','₹31,200 secured in primary beneficiary account','2026-08-29T18:52:00.000Z','inst-hdfc'],['CYBER_CELL_ASSIGNED','Bengaluru Cyber Crime Unit assigned','2026-08-29T19:04:00.000Z','inst-cyber'],['FIR_REVIEW_STARTED','FIR review started','2026-08-29T19:18:00.000Z','inst-police']]; for(const e of events) event('case-golden',e[0],e[1],e[2],e[3]);
 db.prepare("INSERT INTO agency_assignments VALUES(?,?,?,?,?,?,?,?,?)").run('assign-cyber','case-golden','inst-cyber','investigation','acknowledged','2026-08-29T19:04:00.000Z','2026-08-29T19:05:00.000Z',null,now);
 db.prepare("INSERT INTO fir_records VALUES(?,?,?,?,?,?,?,?,?)").run('fir-golden','case-golden','under_review',null,'Bengaluru Cyber Crime Police Station (simulated)',null,'Review is in progress; no FIR outcome has been determined.',now,now);
 db.prepare("INSERT INTO evidence_requests VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('req-golden','case-golden','Bengaluru Cyber Crime Unit','Bank statement needed','Please upload a statement covering 28–29 August.','bank_statement','2026-08-31T17:00:00.000Z','open',null,now,null);
 db.prepare("INSERT INTO notifications VALUES(?,?,?,?,?,?,?,?)").run('note-golden','user-asha','case-golden','case_update','Freeze request sent','A simulated freeze request is awaiting acknowledgement from the beneficiary bank.',null,now);
}
